spring:
  application:
    name: eureka-server
  cloud:
    config:
      enabled: false
eureka:
  instance:
    prefer-ip-address: false
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8761

logging:
  level:
    org.apache.kafka: ERROR
    org.apache.kafka.clients.consumer: ERROR
    org.springframework.cloud.stream.binder.kafka: WARN
    org.springframework.kafka: WARN