spring:
  web:
    error:
      include-message: ALWAYS
  application:
    name: api-gateway-service
  cloud:
    refresh:
      enabled: false
    bus:
      enabled: false
  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: ${SPRING_DATA_REDIS_HOST:localhost}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CASDOOR_ISSUER_URI:http://localhost:8000}
          jwk-set-uri: ${CASDOOR_JWK_SET_URI:http://localhost:8000/.well-known/jwks}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10000ms
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2


eureka:
  client:
    enabled: true
    refresh:
      enable: false
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8089

info:
  app:
    name: "api-gateway"
    description: "Api gateway"
    version: "1.0"
    developed-by: 'yours-truly'


security:
  config:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: 1. Account Service
        url: /api/v1/accounts/v3/api-docs
      - name: 2. Transaction Service
        url: /api/v1/transactions/v3/api-docs
      - name: 3. Payment Service
        url: /api/v1/payments/v3/api-docs