spring:
  application:
    name: payment-service

  web:
    error:
      include-message: ALWAYS
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/accounts}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin}
    pool:
      enabled: true
      initial-size: 1
      max-size: 3
      max-idle-time: 10ms
      max-acquire-time: 5s

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
      server-id: CONFIG-SERVER
    bus:
      enabled: false
    function:
      definition: paymentCompletedProducer
    stream:
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
          auto-add-partitions: true
          auto-alter-topics: true
          auto-create-topics: true
        bindings:
          paymentCompletedProducer-out-0:
            producer:
              configuration:
                retries: 2
                acks: all
                enable.idempotence: true
      bindings:
        paymentCompletedProducer-out-0:
          destination: payment-completed
          producer:
            partition-key-expression: "headers['partitionKey']"
            partition-count: 2

  sql:
    init:
      mode: ALWAYS
      continue-on-error: true
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql


razorpay:
  key-id: ${RAZORPAY_ID:dummy_id}
  key-secret: ${RAZORPAY_SECRET:dummy_secret}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:dummy_webhook_secret}

server:
  port: 8086

eureka:
  client:
    refresh:
      enable: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api/v1/payments/v3/api-docs


logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{X-Correlation-ID}]"
  level:
    org.apache.kafka: ERROR
    org.apache.kafka.clients.consumer: ERROR
    org.springframework.cloud.stream.binder.kafka: WARN
    org.springframework.kafka: WARN


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Payment Service"
    description: "Payment Service"
    version: "1.0"
    developed-by: "Yours Truly"