spring:
  web:
    error:
      include-message: ALWAYS
  application:
    name: transaction-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CASDOOR_ISSUER_URI:http://localhost:8000}
          jwk-set-uri: ${CASDOOR_JWK_SET_URI:http://localhost:8000/.well-known/jwks}
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/accounts}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:admin}
    pool:
      enabled: true
      initial-size: 1
      max-size: 3
      max-idle-time: 30s


  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: ${SPRING_DATA_REDIS_HOST:localhost}

  sql:
    init:
      mode: ALWAYS
      continue-on-error: true
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
      server-id: CONFIG-SERVER
    bus:
      enabled: false

    function:
      definition: transactionInitiatorProducer;transactionCompletedProducer;transactionRefundedProducer;verificationConsumer;otpVerificationProducer;cleanCheckConsumer
    stream:
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
          auto-add-partitions: true
          auto-alter-topics: true
          auto-create-topics: true
        bindings:
          transactionInitiatorProducer-out-0:
            producer:
              configuration:
                retries: 2
                acks: all
                enable.idempotence: true
          transactionCompletedProducer-out-0:
            producer:
              configuration:
                retries: 2
                acks: all
                enable.idempotence: true
          transactionRefundedProducer-out-0:
            producer:
              configuration:
                retries: 2
                acks: all
                enable.idempotence: true
          verificationConsumer-in-0:
            consumer:
              ack-mode: MANUAL
          cleanCheckConsumer-in-0:
            consumer:
              ack-mode: MANUAL
          otpVerificationProducer-out-0:
            producer:
              configuration:
                retries: 2
                acks: all
                enable.idempotence: true

      bindings:
        cleanCheckConsumer-in-0:
          destination: fraud-check-clean
          group: transaction-service-group
        otpVerificationProducer-out-0:
          destination: otp-generation-event
          producer:
            partition-key-expression: "headers['partitionID']"
            partition-count: 2
        verificationConsumer-in-0:
          destination: verify-transaction
          group: transaction-service-group
        transactionInitiatorProducer-out-0:
          destination: transactioninitiated
          producer:
            partition-key-expression: "headers['partitionID']"
            partition-count: 2
        transactionCompletedProducer-out-0:
          destination: transactioncompleted
          producer:
            partition-key-expression: "headers['partitionID']"
            partition-count: 2
        transactionRefundedProducer-out-0:
          destination: transactionrefunded
          producer:
            partition-key-expression: "headers['partitionID']"
            partition-count: 2

eureka:
  client:
    refresh:
      enable: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /api/v1/transactions/v3/api-docs


server:
  port: 8084
logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{X-Correlation-ID}]"
  level:
    org.apache.kafka: ERROR
    org.apache.kafka.clients.consumer: ERROR
    org.springframework.cloud.stream.binder.kafka: WARN
    org.springframework.kafka: WARN
